remote_theme: "riggraz/no-style-please" # This specifies the theme to use
title: "My Awesome Site"
description: "A description of your website"
baseurl: "" # Leave this blank unless it's a project page
url: "https://blauling.github.io" # Replace with your GitHub Pages URL

# Any other theme-specific settings can be added here
