remote_theme: "riggraz/no-style-please" # This specifies the theme to use
title: "My Awesome Site"
description: "A description of your website"
baseurl: "" # Leave this blank unless it's a project page
url: "https://blauling.github.io" # Replace with your GitHub Pages URL

menu:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%d-%m-%Y" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Any other theme-specific settings can be added here
